### ISSUE TITLE
Additive behaviour

### ISSUE THREAD

**Issue by amannn** [chenglou/react-motion#147]
Coming from [your example from react-tween-state](https://rawgit.com/chenglou/react-tween-state/master/examples/index.html): Could it be possible, that react-motion uses the "Slightly smarter Destructive Transition" by default? Is it possible to change this to the additive behaviour?

Thank you very much!

**Comment by chenglou** [comment]
Nope. With a spring, you get the "additive" behavior for free. Actually, the additive behavior for normal easing curves is an escape hatch for those to model a spring, in the sense that you want a smooth curve where you wouldn't get one with an ordinary interrupted e.g. easein (see more explanation [here](http://iosoteric.com/additive-animations-animatewithduration-in-ios-8/)). It also doesn't work on every curve, because math.

Try the demos in the readme and check the code: there's no setup for additive needed =).

**Comment by amannn** [comment]
Your right, thanks for the explanation!

I experimented a bit with the first demo and found that the additive behaviour like in the react-tween-state demo is especially visible with lower dampings. E. g. a spring setup with `[10, 2]` shows a similar behaviour for the interruption (hower it overshoots quite heavily on the edges). So as you said, i guess that's just the way physics animation feels like and you don't see that deceleration in velocity when interrupting so often with most spring settings.
