### ISSUE TITLE
Help on getting started

### ISSUE THREAD

**Issue by olance** [chenglou/react-motion#150]
Hi!

I find the demos and their performance really promising so I'd really love to use react-motion in a project of mine, but I can't get my head around how to use it efficiently (if at all) :\

Here's my use case. I'd appreciate if you could guide me through what's behind `endValue`, `willEnter`, `willLeave` in relation to the life cycle of a component, how to think an animation with those and build it with Spring/TransitionSpring!

I have a text input. When the user enters some text, I open a panel just below the input with some search suggestions. I managed to use a `<Spring>` component to animate the apparition of the panel when a text is first entered.

What I don't get, is how I should use react-motion to animate the panel when it grows/shrinks/disappears depending on the suggestions (or absence of them) I have to present to the user?

To simplify, let's say my panel has three states: 

  1. closed
  2. opened with content (which is not simply a list of <li> elements)
  3. opened with an error message

How can I have animated transitions (using a scaleY transform for instance) from any of these state to another one?
I can't figure out how I could use the key enters/key leaves system of the TransitionSpring...

Thanks for your help!

**Comment by chenglou** [comment]
Wow, this issue got completely skipped for some reason, so sorry!
To answer your question: the todo demo should help. The readme has been revamped since, too.

Closing this since this is old and I suspect you've moved on from it (sorry again for missing this issue). If not, please do check the new docs. If so, closing for now but feel free to reopen. Also, we're on [Discord](https://discordapp.com/invite/0ZcbPKXt5bYzmcI0) =)

**Comment by olance** [comment]
hey @chenglou thanks for replying :)
I have moved to other things indeed, but I'll be interested in learning to use react-motion anyway, so I'll have a look! Thanks!
