### ISSUE TITLE
`defaultValue` should be passed `prevValue`

### ISSUE THREAD

**Issue by akre54** [chenglou/react-motion#154]
Currently the `endValue` prop can be either an object or a function that is passed the `prevValue` and returns an object. Can `defaultValue` also have this feature? It'd be cleaner than using `setState` in my component lifecycle.

**Comment by chenglou** [comment]
Unless I'm missing something, it doesn't make sense to have `defaultValue` as a function accepting `prevValue`, since there's no `prevValue`.
A bit of context: `defaultValue` used to not be there. To animate on mounting, you'd use the conditional check:

```js
endValue={prevValue => prevValue == null ? initConfig : endConfig}
```
But this wasn't discoverable enough, and people made mistakes when they forget to do the null check, which is why I pulled out a `defaultValue` for clarity.

Back on topic: I'm not sure why you'd set your state then pass it to `defaultValue`. You should be able to compute whatever you need directly inside render.

(Closing but let's keep the discussion going.)

**Comment by akre54** [comment]
Perhaps I'm misunderstanding prevValue then. My goal is to treat it like `componentWillUpdate` / `componentDidUpdate` operating on props. Is that the wrong way to think about this?

**Comment by chenglou** [comment]
`defautValue` is only ever used at the very first render, akin to React's `defaultValue` for inputs. So it's likely not what you're imagining. What's your use-case?

**Comment by akre54** [comment]
A line that animates when new data comes in.

http://bost.ocks.org/mike/path/

It looks like the new api for start and end value may be the right way to
go?

On Sat, Sep 12, 2015, 14:01 Cheng Lou <notifications@github.com> wrote:

> defautValue is only ever used at the very first render, akin to React's
> defaultValue for inputs. So it's likely not what you're imagining. What's
> your use-case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chenglou/react-motion/issues/154#issuecomment-139801210>
> .
>
-- 

Adam K (mobile)

**Comment by chenglou** [comment]
Does the shape of `endValue` changes?

**Comment by akre54** [comment]
Shape stays the same.

On Sat, Sep 12, 2015, 14:15 Cheng Lou <notifications@github.com> wrote:

> Does the shape of endValue changes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chenglou/react-motion/issues/154#issuecomment-139806927>
> .
>
-- 

Adam K (mobile)
