### ISSUE TITLE
End-to-end testing

### ISSUE THREAD

**Issue by nkbt** [chenglou/react-motion#223]
I've just implemented one for [react-component-template](https://github.com/nkbt/react-component-template) (with @ButenkoT help)

Look at https://github.com/nkbt/react-component-template/pull/9 for some nice automation (basically installing and running everything with `npm run test:e2e` + prepush hook)

@chenglou do you want to have this sort of testing here?

PS: for each component I publish, I have example, and dev-server. So I can run it and then click through example to make sure it is not broken (at least smoketest). Then I can add more tests to make sure it actually behaves correctly. Testing is done in Chrome, so it is very close to real life.

**Comment by chenglou** [comment]
What would be an example of a concrete test for RM?
As an aside: I'm scared of selenium after using it for some other task, lol

**Comment by nkbt** [comment]
Lol. Forget about selenium, it is a middle layer. You are dealing with
nightwatch, which is pretty neat. Unless you mean something different.
Yeah, selenium itself could be flaky and hard to debug :(.

Regarding tests, firstly some smoketests, check that page loaded and there
are no js errors, so it renders at least something. Then some tests on
actual ui. Animations are hard indeed, but it is still possible to check at
least something to make sure, things are working.

I definitely do not insist on this, just made a suggestion in case you were
like "would be nice to have some sort of e2e, but too much hassle setting
things up" :).

**Comment by chenglou** [comment]
I see. Yeah the idea of e2e would be nice but there's indeed some overhead.

We have the basterdized `test/integration` which verifies that everything's published correctly right now. For animation, I'd rather advance the mock rAF the way it's done in animationLoop-test and components-test right now. Got burnt trying to do screenshot testing too much ([ahem](https://github.com/chenglou/node-huxley)).

I think we're fine for now. I'll leave this issue open because it's a fine idea.

**Comment by nkbt** [comment]
Sure, sounds good. Let's leave it as a backlog feature for future reference.

**Comment by chenglou** [comment]
Still remembering this, but closing it because I'm on an issue closing rampage.

**Comment by nkbt** [comment]
:+1:
