### ISSUE TITLE
Question: Any thoughts on react-motion + Web Animation spec?

### ISSUE THREAD

**Issue by hitsthings** [chenglou/react-motion#240]
I'm only now looking at react-motion. Despite how awesome react-motion looks, the perf implications of style-recalc are not ideal.

Do you have any thoughts on using the near-future [Web Animation APIs](http://www.w3.org/TR/web-animations/) as [seen in Chrome](https://developers.google.com/web/updates/2014/05/Web-Animations-element.animate-is-now-in-Chrome-36) under the hood to deal with realizing the react-motion animations in the DOM?

I would think the API would have to change a little bit or perhaps this would be another library that builds on react-motion. But your react-europe 2015 demos show that you could feed future states to element.animate() to do the actual DOM animation, and in theory you could cancel the animation and replace it with a new one if those precalculated future states are no longer what you predicted they would be.

Is this something that has been discussed at all? Are there reasons it wouldn't work?

Thanks for any guidance!

**Comment by sompylasar** [comment]
These articles could be interesting regarding the question and the animations as a whole:
http://marcgrabanski.com/html5-animation-api/
http://acko.net/blog/animate-your-way-to-glory/
http://acko.net/blog/animate-your-way-to-glory-pt2/

**Comment by chenglou** [comment]
Yep, acko.net has been a great reference! We already do implement a few perf/visual optimizations such as separating the real-life clock with ideal clock. As for smoothing out arbitrary interpolations, [tween-state](https://github.com/chenglou/react-tween-state) solves this (it's the additive animation that one of the articles is talking about, and one that's implemented in iOS 7) but I'd rather just use springs because it makes other things easier too.

@hitsthings: [Here](https://medium.com/@chenglou/react-motion-and-animated-4b3edf671cba)'s the answer to your question. Hopefully we'll reach that stage where we can defer to web animation (or whatever engine it is) under the hood. In the mean time, the next goal would be to defer to actual DOM manipulation. I've been caught up with a few other features (and other stuff in general) recently so this hasn't been done yet. Also, the "coordination" that I'm talking about in my article, the one in RM (dependent/stagger spring, unmounting), needs a bit of API tweaking in order to work with DOM manipulations/web animation, like you said.

So: it's being discussed, not as much as some other API priorities right now but still. I'm trying to make the API as good as possible, while considering that animation perf is one of the areas where we still have to sacrifice API for speed. If you're interested in making the API totally compatible with an arbitrary implementation under the hood, check out #133 (it's slightly messy and deviates from the current implementation; again, if you're interested, give me a signal and I'll revamp it soon).

I'm leaving this open temporarily, in case you have other thoughts on this. Feel free to close it afterward because there are other issues tracking this =)

**Comment by hitsthings** [comment]
I'm still wrapping my head around the proposal in #133 but it makes sense that could support a precalculating backend. I wouldn't make you go through the effort of revamping it just yet - I'm still just finding my way around and wouldn't be able to help implement it or anything.

I appreciate you taking the time to give me all the details on this. It's super helpful.

Cheers!
