### ISSUE TITLE
Todo MVC Demo height does not change if text too long

### ISSUE THREAD

**Issue by sahanDissanayake** [chenglou/react-motion#255]
https://github.com/chenglou/react-motion/tree/master/demos/demo3-todomvc-list-transition
If the text is too long the height does not change dynamically. I'm new to this. So just submitting as a issue as oppose to fixing it

**Comment by chenglou** [comment]
That's weird, I'm testing with a long string and the height does change? Can you show a repro?

**Comment by sahanDissanayake** [comment]
<img width="778" alt="screen shot 2016-01-16 at 9 24 44 pm" src="https://cloud.githubusercontent.com/assets/5580680/12371409/a074cff8-bc97-11e5-8887-4a0f510e761f.png">

**Comment by sahanDissanayake** [comment]
<img width="896" alt="screen shot 2016-01-16 at 9 27 55 pm" src="https://cloud.githubusercontent.com/assets/5580680/12371420/10a4a672-bc98-11e5-93a3-b5471777511f.png">

**Comment by chenglou** [comment]
Oh sorry, that. Yes, in the spirit of keeping the demo simple I've hard-coded the height value. Otherwise height animation gets complicated. Here's an elaborate discussion on animating height: #62

I think I'm gonna close this and mark it as wontfix for this reason. I'll include a demo with variable height one day. Free feel to keep the discussion going.

Thanks for the report!
