### ISSUE TITLE
Name of animation end callback

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#274]
Context: implementing/implemented callback for when a component finishes transitioning. We're not sure yet whether the callback will be applied on the whole component, on the a single style object, or per style value (current implantation for Motion is on the whole component/style object (same thing for Motion since a Motion component has a single style obj), so keep that in mind if you want a future-proof name for this (or not. Maybe it's better to have a specific name for our current implementation, and a different one for a different, e.g. per-value callback).

Potential names:

- `onEnd`
- `onRest`
- `onDone`
- `onStop`
- `onFinish`
- ???

Go ahead!

**Comment by appsforartists** [comment]
I like `onRest` because it doesn't imply finality.  You don't know if an interactive animation/spring is ever finished, because you don't know if the user will interact with the system further; however, you can detect when the system is at rest and notify the application.

I suppose `onStop` could work also, although that implies an abruptness (perhaps that the animation was cancelled).  What we want to convey is that the current animation has completed, without saying anything more about the future state of the system.

**Comment by nkbt** [comment]
`onFinish` from me

**Comment by kottkrig** [comment]
I also like `onRest`. I second @appsforartists reasoning and conclusion.

**Comment by istarkov** [comment]
`onRest` because of similarity with `rebound` onSpringAtRest https://github.com/facebook/rebound-js/blob/master/rebound.js#L730

**Comment by bishopZ** [comment]
onComplete would be more consistent with other libraries.

**Comment by nkbt** [comment]
To elaborate why `rest` is very confusing word.

> `onRest` ~== `onSomethingLeft`. See http://underscorejs.org/#rest for example.

**Comment by appsforartists** [comment]
I don't understand why you would expect it to use that sense of the word rest.  Event names are typically verbs: start, move, end, complete, click, drag, cancel; because they indicate something happening.  Rest, as a verb, means to stop moving, which is what the spring does when it triggers `onRest`.

To name an event with a noun would be a bit bizarre to begin with, but to use rest as a noun would be nonsensical: `onTheRemainingThings`.  I don't even know what that would represent.

Clearly, there's no wrong way to be confused by something and when possible we should avoid confusion.  I'm just surprised that this confuses you, and I doubt many other people will find it confusing because event names are seldom nouns.

**Comment by chakuo** [comment]
@chenglou great to see this being added. But, before this callback mechanism makes it into the API, is there any recommendation about how to unmount a component when a transition ends, like for a page transition. Right now I'm checking for a terminal value like zero to detect when the new page has animated into place, and then not render the previous page.

**Comment by threepointone** [comment]
`onComplete` doesn't make sense for react-motion, because it could be at rest multiple times during its lifetime. (for example - say you feed it a new value every second.) you'd expect it to call `onRest` every time the spring has settled down.

**Comment by nkbt** [comment]
So I guess it is not published yet, right? I mean if `onRest` looks ok - then let it be `onRest`. I personally feel confused, but this sort of bikeshedding is not that important, really ;)

**Comment by dozoisch** [comment]
I agree with onRest. I know "rest" can have multiple different meanings, but the fact that it comes with "on" seems to clear the ambiguity in my opinion.

And I'd really like to have that features because it enable nice "optimization" like stopping things happening before the rest (eg fetching etc) in order to have smoother transitions.

**Comment by kumarharsh** [comment]
`onRest` seems to be good. It's just a meta-stable stage, right?

```
      REST
      ___
     /    \
    /      \ REST
\__/        \____/
```

**Comment by amir-s** [comment]
I wouldn't suggest `onRest`.

Being in rest, is a state, not an event. Animation can be on its rest state for a continuous amounts of time, but something like `onFinish` or `onDone` is like a moment.

**Comment by kumarharsh** [comment]
Finish and Done are also 'continuous amounts of time'. Also, onRest is not equivalent to onFinish/onDone, they are very separate things.

Although I think this discussion is become more pedantic... can we just choose one word and go ahead?

**Comment by CaptainN** [comment]
onRest or any of the antonyms of motion (onIdle, onStagnate, onStillness, onPotentialEnergyStored) would seem to work, though rest feels the most natural/common when describing spring physics.

Pedantically, rest can describe either an event (a state change) or a state - the start of a resting period as in "go rest" or "I will rest when I'm dead", or state as in "at rest".

**Comment by chenglou** [comment]
Thanks for the feedback everyone! Going with what's already there, aka `onRest`, for now =].
