### ISSUE TITLE
Carousel slide animation!

### ISSUE THREAD

**Issue by samarpanda** [chenglou/react-motion#276]
Wondering if its a good practice to animate all items in a slider / carousel when its outside of viewport. Especially those items / slides which are outside of viewport.

**Comment by samarpanda** [comment]
Can anyone clarify my understanding here?

**Comment by threepointone** [comment]
The cost is basically memory - when you have a images per slides etc - even when they're offscreen, they're still uncompressed in RAM, which could be heavy.
CPU - if you have few slides, then the re-rendering cost might not be too bad, but you should keep an eye. 

thus, rendering all items definitely makes for a simpler programming model, but comes with a price.

**Comment by chenglou** [comment]
The new gallery is a simplified version of what I had before. If you dig into past releases you'll see that there was the beginning of TransitionMotion to test some unloading + loading new images logic. I reverted back to using Motion for clarity of demo.

But yes, if it's a gallery with hundred of pictures instead of a demo, you should probably write something more sophisticated =).

[Here](https://github.com/chenglou/react-motion/blob/cc852fe787bb15a8b4a9e51538e03c57d5543d2e/demos/demo4-photo-gallery/Demo.jsx)'s the old code. Hope that helps!

**Comment by samarpanda** [comment]
Thanks @threepointone & @chenglou for the explanation.

![img_20160206_194336](https://cloud.githubusercontent.com/assets/802163/12867161/30ba6288-cd0c-11e5-8c7f-c86e44e7a110.jpg)
Trying to prepare an infinite scroll of images. Loading n images at a time. Thought of having 3 states for images. So, i don't need to scroll all images at a time, rather i can animate two images. One to slideIn other to slideOut. Hope this might help, not hit the performance budget.

**Comment by chenglou** [comment]
if you want slideIn/Out animation then TransitionMotion should do the job. Just pass the array of 3 items styles normally, and specify the willEnter/Leave functions.

**Comment by samarpanda** [comment]
Thanks for the pointer, i will try using TransitionMotion.
