### ISSUE TITLE
Where can I access refs and add event listeners?

### ISSUE THREAD

**Issue by davej** [chenglou/react-motion#280]
Usually I would do it in the `componentDidMount` method but it doesn't have access to the refs of animated elements yet. The code below should explain the problem:

```js
componentDidMount() {
  console.log(this.siteEls); // => [] (empty array, not populated yet)
  // TODO: add custom event listeners to `this.siteEls`
}

render() {
  const { sites } = this.props;
  const siteStyles = sites.map(this.mapStyles);
  this.siteEls = [];

  return (
    <TransitionMotion willEnter={this.willEnter} willLeave={this.willLeave} styles={siteStyles}>
      {styles =>
        <div>
          {styles.map((site, i) =>
            <div key={site.key} ref={div => this.siteEls[i] = div} style={site.style}>
              <Site site={site.data} />
            </div>
          )}
        </div>
      }
    </TransitionMotion>
  );
}
```

**Comment by davej** [comment]
Also the render method of the `<Site>` element in my example above gets called hundreds of times despite the fact that nothing in that component actually needs to get re-rendered during the animation. What is the recommended approach to dealing with scenarios like this? Can I put something in `<Site>`'s `shouldComponentUpdate` to prevent this?

**Comment by davej** [comment]
It looks like #244 is what I need.

**Comment by chenglou** [comment]
As a follow-up to that PR's reply: [React-static-container](https://github.com/reactjs/react-static-container) should solve your problem.

As for refs, how many times is that ref assigning function called? If once, you can add it there (I'm not sure)? If many time, you can do a check whether a listener's there already.

Closing, only because I'm trying to reduce the issue count. Please, feel free to reopen this if you want to follow up =].
