### ISSUE TITLE
Why use HISTORY instead of CHANGELOG.md ?

### ISSUE THREAD

**Issue by vasco3** [chenglou/react-motion#281]

**Comment by chenglou** [comment]
It's the remnant of when I started open sourcing stuff. A couple of repos I was following had HISTORY instead of CHANGELOG instead, so that's what I picked =).

Also, it sounds more newcomer-friendly. I used to go "great length" for newcomer-friendliness, but time and random conventions do wear you down. `source` went back to being `src` and `compiled` went back to being `dist`.

**Comment by vasco3** [comment]
Interesting to know about. Thanks
