### ISSUE TITLE
Demos are not available

### ISSUE THREAD

**Issue by jlevycpa** [chenglou/react-motion#286]
Is chenglou.me down? I can't seem to get to any of the demos, such as: http://chenglou.me/react-motion/demos/demo5-spring-parameters-chooser/

Thank you!

**Comment by mathieumg** [comment]
Same problem here. :+1:

**Comment by chenglou** [comment]
Thanks for the warning! Fixed.

**Comment by mathieumg** [comment]
Still happening for me, is it a DNS propagation thing?

**Comment by chenglou** [comment]
I've "fixed" the problem by disabling my domain. That host was slightly annoying so I stopped my subscription.

The problem was I was redirecting my github pages URLs to my domain. Now they don't anymore. So the links in the demos restarted working. The link in this issue naturally doesn't because it's still directly pointing to my domain.

**Comment by mathieumg** [comment]
I still get redirected to http://chenglou.me/react-motion/demos/demo3-todomvc-list-transition when trying to access http://chenglou.github.io/react-motion/demos/demo3-todomvc-list-transition for example.

**Comment by chenglou** [comment]
Eh, works for me... Cache?

**Comment by mathieumg** [comment]
Probably DNS cache of some form, I'll wait until it fixes itself or look into it at the next React Conf break. :) Thanks for the help!

**Comment by jlevycpa** [comment]
Thanks for taking care of this so quickly!
