### ISSUE TITLE
How to change animation speed?

### ISSUE THREAD

**Issue by aspirisen** [chenglou/react-motion#312]
Hi, maybe this answer is presented in the docs but i haven't found it. How to change velocity of the animation like in the 'React-Europe talk' with Chat Heads ?

**Comment by SleepWalker** [comment]
Hi, you need to variate `stiffnes` and `dumping` of spring config: http://chenglou.github.io/react-motion/demos/demo5-spring-parameters-chooser/

**Comment by crysislinux** [comment]
@SleepWalker Thanks for the answer. But I cannot find a pair of stiffness and dumping to make the animation so slow, like in the 'React-Europe talk' with Chat Heads.

**Comment by sompylasar** [comment]
What's been in the talk is the slowdown of the animation internal timer, not the change in the spring parameters. I don't see this option in the existing API. @chenglou might have an answer.

**Comment by chenglou** [comment]
Sorry for the late reply.

@crysislinux: the slow animation stuff was for debugging and demonstration purposes; it existed as a configuration flag a while ago but I've since removed it for prod (and I hope you didn't need animations _that_ slow in your app =]). That being said, @SleepWalker's link is what I recommend people to use when they don't grasp how to adjust stiffness and damping.

In the next next release (next one is in an hour) I'll add [this](https://github.com/chenglou/react-motion/issues/265#issuecomment-184697874), which will make the situation even better.

Closing! Thanks for the question.

**Comment by sompylasar** [comment]
@chenglou Any plans on adding the debug/demo slowdown functionality back? E.g. Chrome DevTools have got CSS animation slowdown control. Probably we could have some API for slowdown in react-motion? Following the animation loop architecture, this should be a deal of one 0..1 parameter.

**Comment by chenglou** [comment]
There was #158 that tracked it. It wouldn't be too hard to add it back. No idea how the react inspector works though.

**Comment by sompylasar** [comment]
It's not the React inspector, it's the browser core inspector. I doubt we can integrate with it  I just wanted to emphasize that this tool has beem added to Chrome itself, so likely has a demand.

Thanks for pointing to the tracking issue!

**Comment by koutsenko** [comment]
Still no way to get slow animations for dev purposes? 
@chenglou can you explain please, where current animation speed is hardcoded?
I'll make a temporary change in code for myself.
Thanks.
