### ISSUE TITLE
Easy/dumb question on TransitionSpring

### ISSUE THREAD

**Issue by ffxsam** [chenglou/react-motion#314]
Sorry to ask this, but I noticed there are [code examples out there](https://github.com/hayeah/react-motion-TransitionSpring-demo/blob/master/app.jsx) using `TransitionSpring`, yet I don't see this defined anywhere in the code. Is it something being developed offline?

**Comment by chenglou** [comment]
Those are old code; TransitionMotion used to be called TransitionSpring. Here are the details of the change: https://github.com/chenglou/react-motion/wiki/Full-details-0.3.0's-changes.

[Here](https://github.com/chenglou/react-motion/wiki/v0.3.0-examples/_compare/6979da87a095421ad8745193890b7729cfb3a0e3...4d1a6c1072e25ef741ade6551f31ac94d9a58f3b)'s a diff of the changes between the old version you were looking at, and the new version (which itself got a little update since then).

Have a nice day!
