### ISSUE TITLE
Spring object failing to transition and returning NaN

### ISSUE THREAD

**Issue by milesj** [chenglou/react-motion#326]
Not sure how to phrase the title, but what I'm trying to achieve is a `TransitionMotion` that fades children in and out when they are mounted. My progress can be seen here: https://github.com/titon/toolkit/blob/3.0/src/motions/Fade/Group.js It's pretty much copy and paste from examples I have found.

However, I've noticed this weird issue, where the spring objects aren't actually calculating, but string concatenating "NaN" over and over, and does not stop until I kill the page. This can be seen in this screenshot.

<img width="1420" alt="screen shot 2016-05-18 at 23 56 56" src="https://cloud.githubusercontent.com/assets/143744/15385237/03e6abf6-1d55-11e6-9266-8dc33d9bbf8b.png">

I'm having no luck figuring this out. There's been a few instance where it interpolates from 0 to 1 (I log it), but the opacity doesn't actually visually change. I just can't seem to get this to fade.

**Comment by chenglou** [comment]
Your `willEnter`'s return type is wrong, see the docs [here](https://github.com/chenglou/react-motion#--willenter-stylethatentered-transitionstyle--plainstyle). It should be `{opacity: 0, scale: 0.95}` (you want the initial `scale` to be `0.95` right?)

It doesn't make sense for a `willEnter` to specify a spring config, since it's the beginning of the animation. It's the destination position that takes a spring config, aka `styles` and `willLeave`.

You're not the first one to trip on this though. This is unfortunate, and my fault for designing the API this way. I myself use Flow, so these type errors get caught fairly early on. I should consider this more.

Solved (I hope!) and closing. Thanks for the report! =]

**Comment by milesj** [comment]
I've seen a handful of examples where `spring()` was used in `willEnter`. Was that supported at some point, or are all these examples wrong?

I'll give this a shot again and report back.

**Comment by chenglou** [comment]
Those example were using the old API, whose upgrade path I've documented in the wiki. Specifically: https://github.com/chenglou/react-motion/wiki/v0.4.0-examples#motion and https://github.com/chenglou/react-motion/wiki/v0.4.0-examples/_compare/b23bda218bfc5414d2bb70c954c7ed5250e16fa2...6b4990a7adb5a28a633797f2cebc29ff3a21e363

**Comment by milesj** [comment]
Thanks, good to know!
