### ISSUE TITLE
Put some badges

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#33]
Npm/Bower/Slack

**Comment by nkbt** [comment]
devDependencies, CI (circleci?), code coverage (coveralls?)

[![Dependency Status](https://david-dm.org/chenglou/react-motion.svg)](https://david-dm.org/chenglou/react-motion) [![devDependency Status](https://david-dm.org/chenglou/react-motion/dev-status.svg)](https://david-dm.org/chenglou/react-motion#info=devDependencies)

```md

[![Dependency Status](https://david-dm.org/chenglou/react-motion.svg)](https://david-dm.org/chenglou/react-motion)

[![devDependency Status](https://david-dm.org/chenglou/react-motion/dev-status.svg)](https://david-dm.org/chenglou/react-motion#info=devDependencies)
```

**Comment by chenglou** [comment]
Npm bower and slack are fine. Or maybe just slack. Having like 5+ badges is kinda overloading it

**Comment by nkbt** [comment]
=)

you can always put the m the the end of readme. Still nice to have some visual indication that health is OK.

**Comment by srcspider** [comment]
@chenglou Maybe add a gitter link for anything that might require irc-like live chat (help with anything for example). It's easy to use and unlike irc people easily see what people were chatting about before they arrived and can also answer someone even after they leave and the person will just receive an email about it. It's also visible to guests, and you just need github to access it. Here's webpack's as an example: https://gitter.im/webpack/webpack/

Maybe this is just a setting, but Slack presented me with a big "sign up to do anything", and didn't feel like doing that since they presented to me a "hidden steps form" for sign up, but I assume it does something similar to gitter but is more of a private thing for core contributors only?

**Comment by nkbt** [comment]
:+1: for gitter 
:-1: for slack (http://blog.freecodecamp.com/2015/06/so-yeah-we-tried-slack-and-we-deeply-regretted-it.html)

PS: Gitter has IRC gateway https://irc.gitter.im/ which works perfect.

**Comment by chenglou** [comment]
Tbh I'm not much of a slack user and I still find it weird, but I chose slack because the Reactiflux channel already has thousands of users and slack seems more popular than gitter. Popularity sounds like a weak argument but probably not in this case.

Is there any gitter -> slack or irc -> slack integration?

**Comment by srcspider** [comment]
@nkbt didn't know that, awesum

**Comment by gaearon** [comment]
I've heard Slack can be integrated with IRC.
