### ISSUE TITLE
Broken dom update transaction

### ISSUE THREAD

**Issue by oliviertassinari** [chenglou/react-motion#404]
Hi, thanks for this great lib!

Digging around https://github.com/oliviertassinari/react-swipeable-views/issues/192, It seems that the root cause of this issue is right here.

Basically, the style updated is performed ASAP outside of the React `render` transaction leading the interface in an inconsistent state:
I have created a simple reproduction test case:
http://www.webpackbin.com/E1wl7yhMz
![dec -03-2016 17-49-14](https://cloud.githubusercontent.com/assets/3165635/20860779/f17fb098-b980-11e6-9ae2-8ba2648ea7f6.gif)

As you can see with the logs:
#### Initial state

> [Log] interpolatedStyle.translate – 200 (sandbox.webpackbin.com, line 68)
[Log] this.state.children.length – 4 (sandbox.webpackbin.com, line 68)

#### Inconsitancy

> [Log] interpolatedStyle.translate – **200** (sandbox.webpackbin.com, line 68)
[Log] this.state.children.length – **3** (sandbox.webpackbin.com, line 68)

#### End state
> [Log] interpolatedStyle.translate – 100 (sandbox.webpackbin.com, line 68)
[Log] this.state.children.length – 3 (sandbox.webpackbin.com, line 68)

Is this expected? I'm not sure that the best work-around is.

**Comment by yoadsn** [comment]
Maybe i'm over simplifying this problem but from looking at the example you provided:
- After the `setState` call a `render()` is initiated.
- react motion gets a new style with the value of 100 (instead of the `spring(200)`
- state has 3 children instead of 4
- react motion has to render immediately and provides the initial 200 value but with the new state of 3 children
- react motion called from an animation render (without react `render`) with the "final" value of this interpolation which is the immediate 100
- the last render has 100 and 3 children as expected.

So, the react initiated `render()` after the `setState()` must produce a workable component tree and probably is called from the render call itself without the wait for the animation frame that is actually performing the "next step in the interpolation" - in this case setting the value directly to 100. In this "forced render" it must use the new state of 3 children.

I would probably look at using the `<TransitionMotion />` component which also controls the entry and leave of children - in that case the first forced render would still see 4 children although the state changed to 3. On the first animation frame, the children **and** the translate value would change to their end value in sync.

What do you think?

**Comment by yoadsn** [comment]
I have created this modified example:
http://www.webpackbin.com/410YcRxXz

`<TransitionMotion/>` like to operate on the array of children - I had to hack around it so to not change the styles you applied in your example to the parent `<div/>` of the Slides. But of course this could be prettier. Point is, when `react-motion` knows that we removed Slide A - it would wait for the (instant) transition from `spring(200)` to `100` from actually removing it from the rendered children list.

Here is the modified log:

```
react render() // Initial load of the component
Motion - interpolatedStyle.translate 200
Motion - this.state.children.length 4
TransitionMotion - interpolatedStyle.translate 200
TransitionMotion - this.state.children.length 4
TransitionMotion - interpolatedStyles.length 4

react render() // setState() caused this render
Motion - interpolatedStyle.translate 200 // Uses "currentStyle" transition has not started
Motion - this.state.children.length 3 // It must render the existing state.. so 3 children
TransitionMotion - interpolatedStyle.translate 200
TransitionMotion - this.state.children.length 3
TransitionMotion - interpolatedStyles.length 4 // Still "remembers" the children from before

Motion - interpolatedStyle.translate 100 // This is a RAF render - back in sync.
Motion - this.state.children.length 3
TransitionMotion - interpolatedStyle.translate 100
TransitionMotion - this.state.children.length 3
TransitionMotion - interpolatedStyles.length 3
```

And checking on mobile safari the flicker is not visible on the TransitionMotion rendered component.

**Comment by vomchik** [comment]
On safari browser flicker still present.
