### ISSUE TITLE
Extract animation logic so that it can be used outside components

### ISSUE THREAD

**Issue by dariocravero** [chenglou/react-motion#41]
The physics around the motion are super useful for other stuff that might not be React related; e.g., animating scroll - which may need to happen after render.
Would it make sense to extract the animation logic into its own module/function so that it can be used outside React's lifecycle? Am I trying to use this in the wrong way altogether? :) Thanks

**Comment by nkbt** [comment]
I was thinking about exactly the same thing today and it feels like a lot of goodness here comes from React directly. The base logic for re-calculations could be extracted to some `*-core` though and used for non-react apps.

**Comment by dariocravero** [comment]
@chenglou @nkbt [would love to hear your thoughts on this](https://github.com/dariocravero/react-motion/blob/extract-animation-from-spring/src/spring/animate.js)?

**Comment by nkbt** [comment]
Seems ok to me. In terms of syntax I would avoid redefining function argument.

```js
endValue = typeof endValue === 'function' ? endValue(currVals) : endValue;
```

**Comment by nkbt** [comment]
If it is recursive function, could look more interesting with currying

```js
const animate = ({endValue, justStarted}) => ({currV, currVals, now}) =>
  ({currV: xxx, currVals: yyy, now: zzz});
```

**Comment by chenglou** [comment]
Yeah definitely in the future, but not now at least. Issues like https://github.com/chenglou/react-motion/pull/39#issuecomment-120520787 (which I friggin love, thanks @iclanzan @razh!) are exactly why I'm postponing early-refactoring. By the time you're done with the modularization we'd have come up with e.g. a better way of rendering without passing `FRAME_RATE`.

And no, you're not using this the wrong way. Beside `setState` and the component declaration there aren't many React-specific things here (this is intended). But it's been like three days since the official release and we really need to work on the bigger issues (I got gestures coming, maybe =)).

I'm closing this for now because the issues are starting to pile up. Don't worry though, I do have this in mind!

**Comment by dariocravero** [comment]
Good stuff :). It would be really nice to see this become a generic `motion` library and then have bindings for react. It's a pity [motion](https://www.npmjs.com/package/motion) is already taken ;). I'd see that logic being a separate package (motion's core) and any bindings to specific libraries or patterns could then have their own packages that use this.
Would it be a good idea to put a roadmap then?
