### ISSUE TITLE
Clarify currV and currVals

### ISSUE THREAD

**Issue by dariocravero** [chenglou/react-motion#45]
Hi @chenglou, could you shed more light on the `currV` and `currVals`? Have you thought about renaming them to something more meaningful? Thanks :)

**Comment by bsansouci** [comment]
I can explain the little bit that I know. Internally,  `currVals` has the same shape as `destVals` and is the thing evolving towards `destVals`. `currV` is the current velocity, which also has the same shape.

If you have:
```js
let destVals = {
  field1: 10,
  field2: "sadasd",
  field3: {
    nested1: 11,
    nested2: [1, 2, 3, 4]
  }
};
```

Then internally `currVals` and `currV` will look like:
```js
let currVals = {
  field1: ..., // Transitionning between the previous currVals.field1 and 10
  field2: "sadasd", // Doesn't transition
  field3: {
    nested1: ..., // Transitionning between the previous currVals.field3.nested1 
                  // and 11
    nested2: [1, 2, 3, 4] // Each value is transitionning between the previous 
                          // values inside currVals.field3.nested2 and 
                          // [1, 2, 3, 4]
  }
}

let currV = {
  field1: ..., // Velocity at which currVals is transitionning between the 
               // previous currVals.field1 and 10
  field2: "sadasd", // Yes we also keep this (I don't think we need to)
  field3: {
    nested1: ..., // Velocity at which currVals is transitionning between the 
                  // previous currVals.field3.nested1 and 11
    nested2: [1, 2, 3, 4] // Velocity at which Each value in currVals is 
                          // transitionning between the previous values inside 
                          // currVals.field3.nested2 and [1, 2, 3, 4]
  }
}
```

This allows us to have our `Spring` work on any kind of data structure. It also allows us to have `TransitionSpring` use the exact same algorithm with an extra diffing algorithm which assumes the top level of your values are unique keys:

```js
let destVals = {
  "unique1": { // Each of those could be nested, doesn't matter apart from the top level
    text: "blabla",
    opacity: `
  },
  "unique2": {
    text: "blabla2",
    opacity: 0
  },
  "unique3": {
    text: "blabla3",
    opacity: 1
  },
}
```

They both are actually one tick old when we pass them to any user defined function, which would make them more like `intermediateValuesAtLastTick` and `valueVelocitiesAtLastTick`. I think they were intended to be the actual current value of the `Spring` @chenglou?

I think `Spring` was written that way (one tick "late") because it allowed us to not keep the `endValue` in the state of the `Spring` (we always receive it from the props). If we did `endValue(newCurrVals)` at the end of the `raf`  we'd need to keep the return of that call somewhere for the next `raf`. 

This maybe wouldn't such a bad thing in retrospect, for the sake of giving the most up-to-date value to the user? @chenglou @iclanzan what do you guys think?

**Comment by chenglou** [comment]
Not sure how you'd give the most up-to-date current value since it depends on you providing the new `endValue`, which itself would depend on the said "most up-to-date current value". In short, with the current API, you can't. You can receive the `currentValue` from the last tick in `endValue`, and that's good enough since it's mostly used for staggering animation (or is it? I personally haven't found that to be a problem so far).

And yeah all 3 trees are of the same shape, to prevent any confusion/undefined value when the user access either of them in the same way. Pretty important for `willLeave` and `willEnter` too.

**Comment by chenglou** [comment]
Keeping this open because I think I can do a better job of explaining it in README/demos

**Comment by dariocravero** [comment]
Thanks both for the explanation :) What about renaming `currV` to `currentVelocity` and `currVals` to `currentValues` then? I think would make it more explicit and easier to read too. Also, if `currVals` is going to become `endValue` on the next tick, they should probably share the same ending, i.e., `currVal` and `endValue` or `currVals` and `endValues`. With that in mind, perhaps `current` can even be removed altogether from the names, having: `velocity`, `current`, `end`. Thoughts?

**Comment by bsansouci** [comment]
`currValue` and `currVelocity` sound good to me :)

**Comment by chenglou** [comment]
Those were always meant to be temporary names. If you go back in the commit history you'll see more outrageous ones, like `mary` or `epicMergeduce` `meldGoldIntoMold`, lol. Remember that the repo has only been officially released for **three** days (feels like forever?).

I'll check back on this issue once I finish refactoring other stuff.

**Comment by dariocravero** [comment]
Haha I know @chenglou :) the reason for this thread was to raise that question. `meldGoldIntoMold` is just hilarious :P

**Comment by dariocravero** [comment]
Thanks! :)
