### ISSUE TITLE
Further development and maintainment

### ISSUE THREAD

**Issue by DanielRuf** [chenglou/react-motion#544]
Is this project still actively maintained and developed and are you seeking for additional maintainers and contributors who help with the PRs and issues?

**Comment by nkbt** [comment]
So... The state of @nkbt
Due to a good old burn out in the past, at this point my OSS contributions are limited to only critical updates and only if they are affecting my day job projects (so for example when React 17 is released and we actually upgrade, all libs I maintain will be upgraded, but not earlier then that). So basically whatever I can do (and need to) in my working hours - gets updated. I can also occasionally answer some questions and do some code reviews if it is possible to do from the phone (so no actual running examples checks).
We do still use react-motion in our projects quite a bit, so when necessary I do some updates. But certainly not like in "active development/support mode".

**Comment by wswoodruff** [comment]
@nkbt What about bringing on volunteer maintainers to help push through issues and PRs?

**Comment by aaa-magenic-adams** [comment]
@nkbt 
How do we get you these permissions? There's a few more things I'd like out of this library and quite a bit of PRs outstanding.

Or should we fork?
