### ISSUE TITLE
Is the goal of react-motion to eliminate any need for CSS transitions?

### ISSUE THREAD

**Issue by jschr** [chenglou/react-motion#65]
This library is starting to look really awesome! 

I have a few questions about the goals of this library:

1. Do you see react-motion totally replacing the need for css transitions or is it intended to compliment them?

2. Should react-motion be used to transition between hover and active states of a component? Are their any performance implications with doing so?

3. Will we eventually be able to interpolate between color values instead of just integers to transition properties like backgroundColor and borderColor?

Thanks for you great work! Really looking forward to digging into this library in more depth.

**Comment by chenglou** [comment]
Hey!

1. No, because sometimes you really just want a simple little animation on e.g. a small div. CSS transitions great at dealing with this at high perf and little API overhead. That being said, yes, you could use react-motion in these cases.

2. See above. Yes you can. Maybe it's a good idea? I haven't tried these small transitions much yet. This library solves more important problems than to compete against the area CSS transitions are specialized in.

3. You already can, since you can convert your number into a color value. The library doesn't expose any helper for doing so yet, but it should be trivial.

I guess this isn't really an issue so I'll close this. Feel free to keep asking more question below though. Alternatively, you could come sit with us in Slack Reactiflux #react-motion =)

**Comment by jschr** [comment]
Appreciate your response! Ill check out the slack channel too

Thanks
