### ISSUE TITLE
Nesting two springs doesn't work

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#95]
cc @iclanzan because I not sure whether that's a flaw in the current implementation of animation loop of the problem of the (which would be a bigger problem).

Edit: no, I think it's just a flaw in the current implementation.

**Comment by bsansouci** [comment]
There seems to be something very strange happening where the inner Spring would subscribe to the `animationLoop` but never unsubscribe.

I refactored the `animationLoop` code in my [fork](https://github.com/bsansouci/react-motion/blob/dbee34b997b68f36806b3edea8b677da82ad3311/src/animationLoop.js) and it seems to have fixed it.

**Comment by chenglou** [comment]
Maybe because of an inner component update. Anyhow, glad your fork works. We'll release a 2.0.1 if everything goes alright.

**Comment by iclanzan** [comment]
Oh, boy there’s all sorts of weird stuff happening in there when nesting because of repeated/unnecessary render calls.

Let’s say `springB` is nested inside `springA`. The animation starts, `springB` decides it needs to stop, but then in the same tick, during the render/filter phase of the animation loop (the same) props are received through the render function of `springA` registering a new subscription with the animation loop. This new subscription is lost in limbo because filtering doesn’t take into account new items added to the array. As a consequence `springB` does not animate.

**Comment by gaearon** [comment]
At least we don't have threads in JS!

**Comment by nkbt** [comment]
yet!
....webassembly
